# Site settings
title: Robin Peutlschmid
email: rpeutlschmid@gmail.com
remote_theme: jeromelachaud/freelancer-theme
url: https://github.com/jeromelachaud/freelancer-theme
description: "My name is Robin Peutlschmid, and I am a 3D artist, Technical Artist, Environment Artist, Level and Game Designer."
keywords: "your keywords, separated by commas"
skills: "Game Designer - Level Designer - Environment Artist - 3D Artist"
meta_author: Peutlschmid Robin

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: F9F0E1
  primary-rgb: "44, 44, 44"
  secondary: 924E29
  secondary-dark: 755620

# Footer settings
footer:
  copyright: Robin Peutlschmid
  location: Location
  social: Where you can find me
  credits: Contact

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: https://github.com/RobinPeutlschmid
    title: instagram
    url: https://www.instagram.com/robin._artik/
    title: artstation
    url: https://www.artstation.com/neonejd

# Postal address (add as many lines as necessary)
address:
  - line: Brno, Czech repúblic

# Credits content
credits: 'Feel free to contact me through the form or via email at <a href="mailto:rpeutlschmid@gmail.com">rpeutlschmid@gmail.com</a>.'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
